ALTER TABLE Account ADD 
IsDeleted bit DEFAULT 0 
ALTER TABLE Brand ADD 
IsDeleted bit DEFAULT 0 
ALTER TABLE Category ADD 
IsDeleted bit DEFAULT 0 
ALTER TABLE InfoRequest ADD 
IsDeleted bit DEFAULT 0 
ALTER TABLE InfoRequestReply ADD 
IsDeleted bit DEFAULT 0 
ALTER TABLE Nation ADD 
IsDeleted bit DEFAULT 0 
ALTER TABLE Product_Category ADD 
IsDeleted bit DEFAULT 0 
ALTER TABLE [User] ADD 
IsDeleted bit DEFAULT 0 
ALTER TABLE Product ADD 
IsDeleted bit DEFAULT 0 
